### ISSUE TITLE
Any included demos of Janus?

### ISSUE THREAD

**Issue by sepranagw** [janus-project/janusproject#107]
I guess it's not really an 'issue' but I really would like to see a demo of JANUS before I can decide to use it.  I tried installing https://github.com/janus-project/janus-web-sniffer which appears to be a demo of JANUS but it has been difficult to try and install on a non-RPM linux system (I've had to try and install all the necessary dependencies manually, since their install.sh is RPM based, and it's a literal nesting egg of them).    Any ideas are appreciated.

**Comment by gallandarakhneorg** [comment]
Sinec Janus is the platform, and SARL is the language which is used for coding the agents, the demos are available at: https://github.com/sarl/sarl-demos.

Another demo could by found at https://github.com/gallandarakhneorg/jaak in a simulation context.
