### ISSUE TITLE
Purge task launched by a behavior when unregistering this behavior

### ISSUE THREAD

**Issue by ngaud** [janus-project/janusproject#85]
When a behavior is unregistered we currently do not stopped every tasks that have been launched by the corresponding behavior. But normally we must do.

For doing that we must change the code generation to specify the initial launcher of a task, storing them in a map instead of a simple list and then killing them when unregistering the behavior.

**Comment by gallandarakhneorg** [comment]
This issue will be moved into the SARL project according to sarl/sarl#447.

**Comment by gallandarakhneorg** [comment]
This issue was moved to sarl/sarl#459
