### ISSUE TITLE
Thread deadlock problem in agent's destroy function

### ISSUE THREAD

**Issue by ngaud** [janus-project/janusproject#89]
Big problem of thread deadlock when you call a skill in destroy function.

Typical use case:

```
behavior MyBehavior {

	on XX  {  
		killMe
	}
}

agent BehaviorPlayer {
	
	uses Behaviors
	
	var myBehavior : MyBehavior

	  
	on Initialize {
		
		myBehavior = new MyBehavior(this)
		this.registerBehavior(myFactorialBehavior);
		...
	} 

	on Destroy {
		this.unregisterBehavior(myBehavior);
	}


}

```
killMe -> killAgent -> InternalEventBusSkill$AgentListener.killOwner -> iterate over skills uninstallation -> uninstall ExternalContextAccessSkill -> fire context left -> requires BehaviorSkill.wake (synchronized)

In parallel killMe fires destroy event, destroy is executed that calls BehaviorSkill.unregisterBehavior calling InternalEventBusSkill.unregisterEventListener

Basically one thread owns InternalEventBusSkill and waits for BehaviorSkill, and the other owns BehaviorSkill and waits for InternalEventBusSkill: typical deadlock.

The problem is the parallelization of tasks with destroy function.

**Comment by gallandarakhneorg** [comment]
This issue will be moved into the SARL project according to sarl/sarl#447.

**Comment by gallandarakhneorg** [comment]
This issue was moved to sarl/sarl#458
